name: Check
defaults:
  run:
    shell: bash

on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - uses: actions/checkout@v2

      - name: Restore Gradle cache
        id: cache
        uses: actions/cache@v3.0.6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/yarn
            ~/.gradle/nodejs
            ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Gradle Check
        run: ./gradlew check --scan

      - name: Gradle Check Sandbox
        working-directory: sandbox
        run: ./gradlew check --scan

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: reports-${{ runner.os }}
          path: |
            **/build/reports
